import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <main>
        <Header />
        {children}
      </main>
      <SanityLive />
    </ClerkProvider>
  );
}
